import type { Metadata } from "next";

import { Noto_Sans_KR } from "next/font/google";
import "./globals.css";
import { Header } from "@/wigets";
import BackgroundHandler from "./BackgroundHandler";
import AuthSection from "@/wigets/header/ui/AuthSection";
import { SessionProvider } from "@/providers/session";
import LoginModal from "@/wigets/header/LoginModal";
import LoadingSpinner from "@/features/loading/Loading";

const NOTO_SANS_KR = Noto_Sans_KR({
  preload: true,
  subsets: ["latin"],
});
export const metadata: Metadata = {
  title: "Baseball Community",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={NOTO_SANS_KR.className}>
        <SessionProvider>
          <LoadingSpinner />
          <Header />
          <LoginModal />
          {/* <div className="relative">
            <AuthSection />
          </div> */}
          <main className="px-4 bg-gray-100">
            <BackgroundHandler />
            <div className="mx-auto max-w-screen-xl min-h-screen">
              {children}
            </div>
          </main>
        </SessionProvider>
      </body>
    </html>
  );
}
