import type { Metadata } from "next";

import { Noto_Sans_KR } from "next/font/google";
import "./globals.css";
import { Header } from "@/wigets";
import Msw from "./mocks/Msw";

const NOTO_SANS_KR = Noto_Sans_KR({
  preload: true,
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Baseball Community",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <Msw />
      <body className={NOTO_SANS_KR.className}>
        <Header />
        <main className="px-4">
          <div className="mx-auto max-w-screen-xl">{children}</div>
        </main>
      </body>
    </html>
  );
}
